on:
  schedule:
    - cron: '0 0/12 * * *'
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Generate README.md
      uses: teoxoy/profile-readme-stats@v1
      with:
        token: ${{ secrets.README_TOKEN }}
    - name: Update README.md
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name adxl
        git config user.email adelsenhadjii@gmail.com
        git add .
        git commit -m "Update README"
        git push
        fi
